const alt = [
  "Posters about drinking and driving displayed around the drivers education classroom.",
  "Posters about drinking and driving displayed around the drivers education classroom.",
  "Students wear drunk goggles and try to toss a ball into a bucket.",
  "Students test their reflexes on a machine that simulates pressing the brake pedal in a car.",
  "Students test their reflexes on a machine that simulates pressing the brake pedal in a car.",
  "Mr. Sabbadino begins his lesson for the evening.",
  "Mr. Sabbadino shows the class a video.",
  "Mr. Sabbadino shows the class a video.",
  "Mr. Sabbadino hands out a piece of paper to each of his students.",
  "Mr. Sabbadino hands out a piece of paper to each of his students.",
  "Mr. Sabbadino shows the class some material on the overhead projector.",
  "Mr. Sabbadino shows the class some material on the overhead projector.",
  "Mr. Sabbadino shows the class some material on the overhead projector.",
  "A student begins her driving lesson behind the wheel.",
  "A student begins his driving lesson in the parking lot.",
  "Mr. Sabbadino explains a driving exercise to his student.",
  "A driving student backs up until the rear bumper touches the cone.",
  "A driving student weaves the car between the cones.",
  "A driving student eases the car forward until the from bumper touches the cone.",
  "Mr. Sabbadino and his two students continue their driving lesson on the road.",
  "A student drives down a four-lane road in the drivers education car with Mr. Sabbadino.",
  "The front end of the drivers education car as a student drives down the road.",
  "A driving student uses his blinker before changing lanes.",
  "A driving student uses his blinker before making a right on red.",
  "A student drives down a two-lane road in the drivers education car with Mr. Sabbadino.",
  "A student drives down a two-lane road in the drivers education car with Mr. Sabbadino.",
  "A former student jumps for joy because she just got her license!",
  "Mr. Sabbadino with Jocelyn Brazeal, winner of the 2018 SCDTSEA poster contest.",
  "Mr. Sabbadino with Claire Swartz, winner of the 2019 SCDTSEA poster contest.",
  "Judah Smith's poster entered in the 2015 SCDTSEA poster contest. (1st place)",
  "Joseph Calamia's poster entered in the 2015 SCDTSEA poster contest. (3rd place)",
  "Emily Smith's poster entered in the 2017 SCDTSEA poster contest. (1st place)",
  "Leah Buffalino's poster entered in the 2017 SCDTSEA poster contest. (2nd place)",
  "Emma Fordham's poster entered in the 2017 SCDTSEA poster contest. (3rd place)",
  "Claire Swartz's poster entered in the 2019 SCDTSEA poster contest. (1st place)",
  "Owen Nigh's poster entered in the 2020 SCDTSEA poster contest. (1st place)",
  "Sophia Gray's poster entered in the 2020 SCDTSEA poster contest. (2nd place)",
  "Matthew Troyer's poster entered in the 2021 SCDTSEA poster contest. (1st place)",
  "Bethany Poteat's poster entered in the 2021 SCDTSEA poster contest. (2nd place)",
  "Daniel Wokaty's poster entered in the 2021 SCDTSEA poster contest. (3rd place)",
  "Elle Gafken's poster entered in the 2022 SCDTSEA poster contest. (1st place)",
  "Mr. Sabbadino with Savannah Hall, winner of SCDTSEA's 2024 \"Sabbadino\" poster contest."
];

module.exports = alt.map((altText, index) => ({
  number: index + 1,
  alt: altText
}));
